export const ALL_GIVEBOOK_REQUEST = "ALL_GIVEBOOK_REQUEST";
export const ALL_GIVEBOOK_SUCCESS = "ALL_GIVEBOOK_SUCCESS";
export const ALL_GIVEBOOK_FAIL = "ALL_GIVEBOOK_FAIL";

export const ADMIN_GIVEBOOK_REQUEST = "ADMIN_GIVEBOOK_REQUEST";
export const ADMIN_GIVEBOOK_SUCCESS = "ADMIN_GIVEBOOK_SUCCESS";
export const ADMIN_GIVEBOOK_FAIL = "ADMIN_GIVEBOOK_FAIL";

export const NEW_GIVEBOOK_REQUEST = "NEW_GIVEBOOK_REQUEST";
export const NEW_GIVEBOOK_SUCCESS = "NEW_GIVEBOOK_SUCCESS";
export const NEW_GIVEBOOK_RESET = "NEW_GIVEBOOK_RESET";
export const NEW_GIVEBOOK_FAIL = "NEW_GIVEBOOK_FAIL";

export const UPDATE_GIVEBOOK_REQUEST = "UPDATE_GIVEBOOK_REQUEST";
export const UPDATE_GIVEBOOK_SUCCESS = "UPDATE_GIVEBOOK_SUCCESS";
export const UPDATE_GIVEBOOK_RESET = "UPDATE_GIVEBOOK_RESET";
export const UPDATE_GIVEBOOK_FAIL = "UPDATE_GIVEBOOK_FAIL";

export const DELETE_GIVEBOOK_REQUEST = "DELETE_GIVEBOOK_REQUEST";
export const DELETE_GIVEBOOK_SUCCESS = "DELETE_GIVEBOOK_SUCCESS";
export const DELETE_GIVEBOOK_RESET = "DELETE_GIVEBOOK_RESET";
export const DELETE_GIVEBOOK_FAIL = "DELETE_GIVEBOOK_FAIL";

export const GIVEBOOK_DETAILS_REQUEST = "GIVEBOOK_DETAILS_REQUEST";
export const GIVEBOOK_DETAILS_SUCCESS = "GIVEBOOK_DETAILS_SUCCESS";
export const GIVEBOOK_DETAILS_FAIL = "GIVEBOOK_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
