export const ALL_WANTBOOK_REQUEST = "ALL_WANTBOOK_REQUEST";
export const ALL_WANTBOOK_SUCCESS = "ALL_WANTBOOK_SUCCESS";
export const ALL_WANTBOOK_FAIL = "ALL_WANTBOOK_FAIL";

export const ADMIN_WANTBOOK_REQUEST = "ADMIN_WANTBOOK_REQUEST";
export const ADMIN_WANTBOOK_SUCCESS = "ADMIN_WANTBOOK_SUCCESS";
export const ADMIN_WANTBOOK_FAIL = "ADMIN_WANTBOOK_FAIL";

export const NEW_WANTBOOK_REQUEST = "NEW_WANTBOOK_REQUEST";
export const NEW_WANTBOOK_SUCCESS = "NEW_WANTBOOK_SUCCESS";
export const NEW_WANTBOOK_RESET = "NEW_WANTBOOK_RESET";
export const NEW_WANTBOOK_FAIL = "NEW_WANTBOOK_FAIL";

export const UPDATE_WANTBOOK_REQUEST = "UPDATE_WANTBOOK_REQUEST";
export const UPDATE_WANTBOOK_SUCCESS = "UPDATE_WANTBOOK_SUCCESS";
export const UPDATE_WANTBOOK_RESET = "UPDATE_WANTBOOK_RESET";
export const UPDATE_WANTBOOK_FAIL = "UPDATE_WANTBOOK_FAIL";

export const DELETE_WANTBOOK_REQUEST = "DELETE_WANTBOOK_REQUEST";
export const DELETE_WANTBOOK_SUCCESS = "DELETE_WANTBOOK_SUCCESS";
export const DELETE_WANTBOOK_RESET = "DELETE_WANTBOOK_RESET";
export const DELETE_WANTBOOK_FAIL = "DELETE_WANTBOOK_FAIL";

export const WANTBOOK_DETAILS_REQUEST = "WANTBOOK_DETAILS_REQUEST";
export const WANTBOOK_DETAILS_SUCCESS = "WANTBOOK_DETAILS_SUCCESS";
export const WANTBOOK_DETAILS_FAIL = "WANTBOOK_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
